import Link from 'next/link'
import { notFound } from 'next/navigation'

import { StageRail, type RailStage } from '@/components/journey/stage-rail'
import { buttonVariants } from '@/components/ui'
import { stageHasRun } from '@/lib/artifacts'
import { STAGES } from '@/lib/stages'
import { findProject } from '@/lib/workspace'

export const dynamic = 'force-dynamic'

/**
 * The journey shell: every stage page renders inside this.
 *
 * The rail's run-status is computed here, once, rather than inside each stage -
 * so the sequence always shows the same truth no matter which stage you landed
 * on, and a stage page never has to know about its siblings.
 */
// `LayoutProps` is generated by Next's typed-routes pass and declares `params`
// as `Promise<unknown>`; annotating it more narrowly fails the generated
// validator, so the cast happens here instead, once, where the route pattern
// above states what the shape actually is.
export default async function ProjectLayout({
  children,
  params,
}: LayoutProps<'/project/[slug]'>) {
  const { slug } = (await params) as { slug: string }
  const project = await findProject(slug)
  if (!project) notFound()

  const stages: RailStage[] = await Promise.all(
    STAGES.map(async (stage) => ({ ...stage, hasRun: await stageHasRun(slug, stage) })),
  )
  const completed = stages.filter((stage) => stage.hasRun).length

  return (
    <div className="flex flex-col gap-8 lg:flex-row lg:gap-10">
      <aside className="lg:w-56 lg:shrink-0">
        <div className="lg:sticky lg:top-24">
          <div className="mb-4 flex flex-col gap-1 px-3">
            <Link
              href={`/project/${slug}`}
              className="truncate text-body font-semibold text-text hover:text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus-ring"
            >
              {project.displayName}
            </Link>
            <p className="text-label uppercase tracking-wide text-text-tertiary">
              {completed} of {stages.length} stages complete
            </p>
          </div>

          {/* Horizontal scroll on mobile keeps all nine reachable without a
              menu; the rail is the navigation, so it must never be hidden. */}
          <div className="-mx-4 overflow-x-auto px-4 lg:mx-0 lg:overflow-visible lg:px-0">
            <StageRail
              slug={slug}
              stages={stages}
              className="min-w-max flex-row gap-2 lg:min-w-0 lg:flex-col lg:gap-1"
            />
          </div>

          <div className="mt-6 hidden px-3 lg:block">
            <Link href="/" className={buttonVariants({ variant: 'secondary', size: 'sm' })}>
              New analysis
            </Link>
          </div>
        </div>
      </aside>

      <div className="min-w-0 flex-1">{children}</div>
    </div>
  )
}
